routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\SpreadsheetController;
use App\Http\Controllers\DispatchController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('campaigns', CampaignController::class);

    Route::resource('spreadsheets', SpreadsheetController::class);

    Route::get('dispatch/{file}', [DispatchController::class, 'send'])->name('dispatch.send.file');
});

require __DIR__.'/auth.php';

app/Models/Campaign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Campaign extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name'
    ];

    public function files()
    {
        return $this->hasMany(File::class);
    }
}

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;

    protected $fillable = [
        'campaign_id', 'user_id', 'name'
    ];

    public function campaign()
    {
        return $this->hasOne(Campaign::class);
    }

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function spreadsheet()
    {
        return $this->hasMany(Spreadsheet::class);
    }
}

app/Models/Spreadsheet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Spreadsheet extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
      'campaigns_id', 'file_id', 'item', 'status'
    ];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Models\Campaign;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Rap2hpoutre\FastExcel\FastExcel;


class CampaignController extends Controller
{

    public function index()
    {
        //
    }


    public function create()
    {
        return view('campaign.create');
    }


    public function store(Request $request)
    {
        $campaign = Campaign::create($request->all());

        return redirect(route('spreadsheets.show', $campaign->id));
    }


    public function show(Campaign $campaign)
    {
        return view('campaign.show', compact('campaign'));
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/DispatchController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SpreadsheetMail;
use App\Models\Campaign;
use App\Models\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class DispatchController extends Controller
{
    public function send(File $file)
    {
        foreach($file->spreadsheet()->get() as $item)
        {

            $spreadsheet_itens = $this->parse_params($item->item);

            foreach(json_decode($item->item) as $key => $params)
            {
                if ($key == "EMAIL"){
                    $details = [
                        'campaign_id' => $file->campaign_id,
                        'data' => $spreadsheet_itens
                    ];

                    Mail::to($params)
                        ->send(
                            new SpreadsheetMail($details)
                        );
                }
            }
        }
    }

    public function parse_params($params)
    {
        $result = [];

        foreach(json_decode($params) as $key => $params)
        {
            $key_parsed = str_replace("-", "_", $key);

            $result[$key_parsed] = $params;
        }

        return $result;
    }
}

app/Http/Controllers/SpreadsheetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Campaign;
use App\Models\File;
use App\Models\Spreadsheet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SpreadsheetController extends Controller
{

    public function index()
    {
        //
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        if ($request->hasFile('file'))
        {

            $file = $request->file('file');

            $file_spread = File::create([
                'campaign_id'   => $request->get('campaign_id'),
                'user_id'       => Auth::user()->id,
                'name'          => $file->getClientOriginalName(),
            ]);

            $csv = array_map('str_getcsv', file($file));
            array_walk($csv, function(&$a) use ($csv) {
                $a = array_combine($csv[0], $a);
            });
            array_shift($csv); # remove column header

            foreach ($csv as $sheet)
            {
                $data = [
                    'campaigns_id'  => (int)$request->get('campaign_id'),
                    'file_id'       => $file_spread->id,
                    'item'          => json_encode($sheet),
                    'status'        => false
                ];

                Spreadsheet::create($data);
            }
        }

        return redirect(route('spreadsheets.show', $request->get('campaign_id')))->with(['success' => true]);
    }


    public function show($id)
    {
        $campaing = Campaign::find($id);

        return view('spreadsheet.show', compact('campaing'));
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/campaign/create.blade.php
<x-app-layout>
    <x-header>
        <x-slot name="page_title">Nova campanha</x-slot>
        <x-slot name="page_bradcrumb">
            <div>
                <a href="javascript:void(0);" class="fs-18 text-primary font-w600">Campanha / </a>
                <a href="javascript:void(0);" class="fs-18">Criar nova campanha</a>
            </div>
        </x-slot>
    </x-header>

    <x-profile-slidebar></x-profile-slidebar>

    <div class="content-body">
        <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12 col-xxl-12 col-lg-12">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header pb-0 border-0">
                                <h3 class="fs-20 text-black">Descreva a campanha</h3>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{ route('campaigns.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-row">
                                        <div class="form-group col-xl-12">
                                            <label class="text-black font-w500 mb-3">Nome/Apelido</label><span class="text-danger ml-1">*</span>
                                            <input type="text" name="name" class="form-control" placeholder="">
                                        </div>

                                    </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-xl-12">


                        <div class="form-row">
                            <div class="form-group col-xl-12">
                                <x-button>Cadastrar</x-button>
                            </div>
                        </div>

                    </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>


</x-app-layout>

resources/views/campaign/show.blade.php
<x-app-layout>
    <x-header>
        <x-slot name="page_title">Campanha -> {{ $campaign->name }}</x-slot>
        <x-slot name="page_bradcrumb">
            <div>
                <a href="javascript:void(0);" class="fs-18 text-primary font-w600">Campanha / </a>
                <a href="{{ route('campaigns.show', $campaign->id) }}" class="fs-18 text-primary font-w600">{{ $campaign->name }} /</a>
                <a href="javascript:void(0);" class="fs-18">Status da campanha</a>
            </div>
        </x-slot>
    </x-header>

    <x-profile-slidebar></x-profile-slidebar>

    <div class="content-body">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Arquivos da campanha ({{$campaign->files()->count()}})</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-responsive-md">
                                    <thead>
                                    <tr>
                                        <th><strong>NOME</strong></th>
                                        <th><strong>USUARIO</strong></th>
                                        <th><strong>DATE</strong></th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($campaign->files()->get() as $file)
                                        <tr>
                                            <td>{{ $file->name }}</td>
                                            <td>{{ $file->user->name }}</td>
                                            <td>{{ $file->created_at->format('d/m/Y')}}</td>
                                            <td>
                                                @if(!$file->status)
                                                    <a href="{{ route('dispatch.send.file', $file->id) }}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-feed"></i></a>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/index.blade.php
<x-app-layout>
    <x-header>
        <x-slot name="page_title">Dashboard</x-slot>
        <x-slot name="page_bradcrumb">Seja Bem vindo</x-slot>
    </x-header>

    <x-profile-slidebar></x-profile-slidebar>

    <div class="content-body">
        <div class="container-fluid">

        <div class="row">
            <div class="col-lg-8 col-xxl-12">
                <div class="row">
                    <div class="col-lg-6 col-sm-6">
                        <div class="card widget-stat ">
                            <div class="card-body p-4">
                                <div class="media align-items-center">
                                    <div class="media-body">
                                        <p class="fs-18 mb-2 wspace-no">Total Planilhas</p>
                                        <h1 class="fs-36 font-w600 text-black mb-0">3</h1>
                                    </div>
                                    <span class="ml-3 bg-primary text-white">
												<i class="flaticon-381-promotion"></i>
											</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card widget-stat">
                            <div class="card-body p-4">
                                <div class="media align-items-center">
                                    <div class="media-body">
                                        <p class="fs-18 mb-2 wspace-no">Total Envios</p>
                                        <h1 class="fs-36 font-w600 d-flex align-items-center text-black mb-0">3</h1>
                                    </div>
                                    <span class="ml-3 bg-warning text-white">
												<i class="flaticon-381-user-7"></i>
											</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-body d-flex flex-wrap p-0">
                                <div class="col-lg-6 col-sm-6  media spending-bx">
                                    <div class="spending-icon mr-4">
                                        <i class="fa fa-caret-up" aria-hidden="true"></i>
                                        <span class="fs-14">+5%</span>
                                    </div>
                                    <div class="media-body">
                                        <p class="fs-18 mb-2">Campanhas</p>
                                        <span class="fs-34 font-w600">23</span>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-6 media spending-bx pl-2">
                                    <div class="media-body text-right">
                                        <p class="fs-18 mb-2">Envios</p>
                                        <span class="fs-34 font-w600">3</span>
                                    </div>
                                    <div class="spending-icon ml-4">
                                        <i class="fa fa-caret-down" aria-hidden="true"></i>
                                        <span class="fs-14">-2%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
    </div>
</x-app-layout>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link href="./css/style.css" rel="stylesheet">

    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
    <script src="{{asset('vendor/global/global.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-select/dist/js/bootstrap-select.min.js')}}></script>
    <script src="{{asset('js/custom.min.js')}}></script>
    <script src="{{asset('js/deznav-init.js')}}></script>
</html>

resources/views/layouts/navigation.blade.php
<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Dashboard</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="#">Estatisticas</a></li>
                    <li><a href="#">Campanhas</a></li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-381-television"></i>
                    <span class="nav-text">Campanhas</span>
                </a>
                <ul aria-expanded="false">
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Campanhas</a>
                        <ul aria-expanded="false">
                            <li><a href="#">Nova</a></li>
                            <li><a href="#">Enviar</a></li>
                            <li><a href="#">Visualizar</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-381-controls-3"></i>
                    <span class="nav-text">Configuracoes</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="./chart-flot.html">Configuracoes e-mail</a></li>
                </ul>
            </li>

        </ul>
        <div class="copyright">
            <p><strong>FingerPrint</strong> | Mananger<br/>© {{ now()->format('Y')}}</p>
        </div>
    </div>
</div>

resources/views/spreadsheet/create.blade.php
<x-app-layout>
    <x-header>
        <x-slot name="page_title">Nova campanha</x-slot>
        <x-slot name="page_bradcrumb">
            <div>
                <a href="javascript:void(0);" class="fs-18 text-primary font-w600">Campanha / </a>
                <a href="javascript:void(0);" class="fs-18">Criar nova campanha</a>
            </div>
        </x-slot>
    </x-header>

    <x-profile-slidebar></x-profile-slidebar>

    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-12 col-xxl-12 col-lg-12">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-header pb-0 border-0">
                                    <h3 class="fs-20 text-black">Descreva a campanha</h3>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="{{ route('campaigns.store') }}" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-row">
                                            <div class="form-group col-xl-12">
                                                <label class="text-black font-w500 mb-3">Planilha (CSV)</label><span class="text-danger ml-1">*</span>
                                                <input type="file" name="file" class="form-control">
                                            </div>
                                        </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-xl-12">


                            <div class="form-row">
                                <div class="form-group col-xl-12">
                                    <x-button>Cadastrar</x-button>
                                </div>
                            </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


</x-app-layout>

resources/views/spreadsheet/show.blade.php
<x-app-layout>
    <x-header>
        <x-slot name="page_title">Enviar CSV -> {{ $campaing->name }}</x-slot>
        <x-slot name="page_bradcrumb">
            <div>
                <a href="javascript:void(0);" class="fs-18 text-primary font-w600">Campanha / </a>
                <a href="{{ route('campaigns.show', $campaing->id) }}" class="fs-18 text-primary font-w600">{{ $campaing->name }} /</a>
                <a href="javascript:void(0);" class="fs-18">Enviar CSV</a>
            </div>
        </x-slot>
    </x-header>

    <x-profile-slidebar></x-profile-slidebar>

    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-12 col-xxl-12 col-lg-12">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-header pb-0 border-0">
                                    <h3 class="fs-20 text-black">Envie o arquivo CSV</h3>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="{{ route('spreadsheets.store') }}" enctype="multipart/form-data">
                                        @csrf
                                        <input type="hidden" name="campaign_id" value="{{ $campaing->id }}">
                                        <div class="form-row">
                                            <div class="form-group col-xl-12">
                                                <label class="text-black font-w500 mb-3">Planilha (CSV)</label><span class="text-danger ml-1">*</span>
                                                <input type="file" name="file" class="form-control">
                                            </div>
                                        </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-xl-12">


                            <div class="form-row">
                                <div class="form-group col-xl-12">
                                    <x-button>Cadastrar</x-button>
                                </div>
                            </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Arquivos da campanha ({{$campaing->files()->count()}})</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-responsive-md">
                                    <thead>
                                    <tr>
                                        <th><strong>NOME</strong></th>
                                        <th><strong>USUARIO</strong></th>
                                        <th><strong>DATE</strong></th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($campaing->files()->get() as $file)
                                    <tr>
                                        <td>{{ $file->name }}</td>
                                        <td>{{ $file->user->name }}</td>
                                        <td>{{ $file->created_at->format('d/m/Y')}}</td>
                                    </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</x-app-layout>